version: 2
general:
  artifacts:

do_steps: &do_steps
 steps:
  - run: echo "$CROSS_COMPILE" > ~/_cross_compile
  - restore_cache:
      key: code-tree-shallow-{{ .Environment.CACHE_VERSION }}
  - run:
      name: checkout build tree
      command: |
        mkdir -p ~/.ssh/
        pacman -Syy;
        pacman -S openssh --noconfirm;
        pacman -S git wget unzip zip --noconfirm
        pacman -S jdk11-openjdk --noconfirm
        source /etc/profile.d/jre.sh
        export JAVA_HOME=/usr/lib/jvm/java-11-openjdk/
        ssh-keyscan -H github.com >> ~/.ssh/known_hosts
        git clone $CIRCLE_REPOSITORY_URL ~/project;
        wget -c https://archive.org/download/data.bin_202301/data.bin
        mv data.bin /root/project/archriscv-app/app/src/main/assets/environment/data.bin
        git reset --hard $CIRCLE_SHA1
  - run:
      name: clean app
      command: |
        export JAVA_HOME=/usr/lib/jvm/java-11-openjdk/
        source /etc/profile.d/jre.sh
        cd ~/project
        cd archriscv-app
        ./scripts/setup-android-sdk.sh
        JAVA_HOME=/usr/lib/jvm/java-11-openjdk/ ./gradlew clean
  - run:
      name: build apk-release app
      command: |
        export JAVA_HOME=/usr/lib/jvm/java-11-openjdk/
        source /etc/profile.d/jre.sh
        cd ~/project
        cd archriscv-app
        JAVA_HOME=/usr/lib/jvm/java-11-openjdk/ ./gradlew build
        cd ~/project/archriscv-app/app/build/outputs/apk/release/
        zip -r archlinux-riscv64-term.apk.zip app-release.apk
  - run:
      name: clean float
      command: |
        export JAVA_HOME=/usr/lib/jvm/java-11-openjdk/
        source /etc/profile.d/jre.sh
        cd ~/project
        cd archriscv-float
        JAVA_HOME=/usr/lib/jvm/java-11-openjdk/ ./gradlew clean
  - run:
      name: build apk-release float
      command: |
        export JAVA_HOME=/usr/lib/jvm/java-11-openjdk/
        source /etc/profile.d/jre.sh
        cd ~/project
        cd archriscv-float
        JAVA_HOME=/usr/lib/jvm/java-11-openjdk/ ./gradlew build
        cd ~/project/archriscv-float/app/build/outputs/apk/release/
        zip -r archlinux-riscv64-term-float.apk.zip app-release.apk
  - store_artifacts:
      path: ~/project/archriscv-app/app/build/outputs/apk/release/archlinux-riscv64-term.apk.zip
      destination: archlinux-riscv64-term.apk.zip
  - store_artifacts:
      path: ~/project/archriscv-float/app/build/outputs/apk/release/archlinux-riscv64-term-float.apk.zip
      destination: archlinux-riscv64-term-float.apk.zip
## Customize the test machine
jobs:
  android-aarch64:
   docker:
     - image: archlinux:latest
   environment:
     CROSS_COMPILE: "aarch64-linux-android-"
   <<: *do_steps

workflows:
  version: 2
  build:
    jobs:
     - android-aarch64

